### ISSUE TITLE
Release of new version to npm?

### ISSUE THREAD

**Issue by joyrexus** [andrewbrg/rulepilot#2]
Hey, curious if the updated version ([1.2.0](https://github.com/andrewbrg/rulepilot/blob/main/package.json#L3)), with the new `contains` and `contains any` operators, is going to be published to npm? It looks like [npm still only has has version 1.1.12](https://www.npmjs.com/package/rulepilot).

Thanks in advance!

**Comment by andrewbrg** [comment]
Hi @joyrexus This was published a while back.
