### ISSUE TITLE
expected to not require 'all, any, none' for condition?

### ISSUE THREAD

**Issue by z1haze** [andrewbrg/rulepilot#4]
Hi, awesome library btw!

I wanted to ask if it was intentional that you readme shows using conditions without they all/any/none keyword. I'm scanning the code and I see that it will return false in any event that one is not present, although the docs show this as an example:

```ts
const rule: Rule = {
  conditions: [
    {
      field: "profile.age",
      operator: ">=",
      value: 18,
    },
  ],
};
```

**Comment by andrewbrg** [comment]
Hi @z1haze sorry for the super late reply, I have not checked this repo in a long time. Yea i think it's not correct in the docs, i'll fix it :)
